BMW SALES PROJECT

-- Create Datatbase for BMW Sales data
CREATE DATABASE [BMW sales DB]

-- View the data
SELECT TOP 10 * FROM [BMW sales table];


-- COUNT OF TOTAL RECORD
SELECT COUNT(*) AS TOTAL_RECORD
FROM [BMW sales table]; -- 50,000.


-- DISTINCE VALUES FOR KEY COLUMNS
SELECT 
	COUNT(DISTINCT model) AS MODEL_COUNT,
	COUNT(DISTINCT Color) AS COULOR_COUNT,
	COUNT(DISTINCT Year) AS YEARS_COUNT,
	COUNT(DISTINCT Fuel_Type) AS FUEL_TYPE_COUNT,
	COUNT(DISTINCT Region) AS REGION_COUNT,
	COUNT(DISTINCT Transmission) AS TRANSMISSION_COUNT
FROM [BMW sales table];


-- DISTINCT COUNT FOR UNIQUE COLUMN 
-- COUNT BY MODEL
SELECT
	model,
	COUNT(*) AS ModeL_counts
FROM [BMW sales table]
GROUP BY Model
ORDER BY Model DESC;

-- TOTAL SALES VOLUME, AVERAGE PRICE AND MILEAGE BY MODEL.
SELECT
	model,
	SUM(Sales_Volume) AS TOTAL_SALESVOLUME,
	ROUND(AVG(Price_USD), 0) AS AVERAGE_PRICE,
	AVG(Mileage_KM) AS AVERAGE_MILEAGE
FROM [BMW sales table]
GROUP BY Model
ORDER BY TOTAL_SALESVOLUME DESC;

-- TOTAL SALES VOLUME BY REGION.
SELECT
	Region,
	ROUND(AVG(Price_USD), 2) AS AVG_PRICE,
	SUM(Sales_Volume) AS TOTAL_SALES
FROM [BMW sales table]
GROUP BY Region
ORDER BY TOTAL_SALES DESC;


-- TRANSMISSION PERFORMANCE
SELECT 
	Transmission,
	SUM(Sales_Volume) AS TOTAL_SALES
FROM [BMW sales table]
GROUP BY Transmission
ORDER BY TOTAL_SALES DESC;


-- FUEL TYPE PERFORMANCE
SELECT
	Fuel_Type,
	SUM(Sales_Volume) AS TOTAL_SALES,
	ROUND(AVG(Price_USD),2) AS AVERAGE_PRICE
FROM [BMW sales table]
GROUP BY Fuel_Type
ORDER BY TOTAL_SALES DESC

--SALES TREND BY YEAR
SELECT
	Year,
	SUM(Sales_Volume) AS TOTAL_SALES
FROM [BMW sales table]
GROUP BY Year
ORDER BY TOTAL_SALES DESC


